few_shots = [
        {'Question' : "How many t shirts stock quantity do we have left for nike in small size and white color",
        'SQLQuery' : "SELECT SUM(stock_quantity) FROM t_shirts WHERE brand = 'Nike' AND size = 'S' AND color = 'White'",
        'SQLResult' : "Result of the SQL query",
        'Answer' : '75'},
        {'Question' : "How much is the price of the inventory for all small size t shirts",
        'SQLQuery' : "SELECT SUM(price * stock_quantity) FROM t_shirts WHERE size = 'S'",
        'SQLResult' : "Result of the SQL query",
        'Answer' : '17547'},
        {'Question' : "If we have to sell all the Levi's t shirts today with discounts applied. How much revenue the store will generate(Post discounts)",
        'SQLQuery' : "select sum(a.total_amount * ((100-COALESCE(discounts.pct_discount,0))/100)) as total_revenue from (select sum(price*stock_quantity) as total_amount, t_shirt_id from t_shirts where brand ='Levi' group by t_shirt_id) a left join discounts on a.t_shirt_id = discounts.t_shirt_id",
        'SQLResult' : "Result of the SQL query",
        'Answer' : '19638.20'},
        {'Question' : "If we have to sell all the Levi's T-shirts today, How much revenue our store will get",
        'SQLQuery' : "SLECT SUM(price * stock_quantity) FROM t_shirts WHERE brand = 'Levi'",
        'SQLResult' : "Result of the SQL query",
        'Answer' : '21541'},
        {'Question' : "How much white color Levi's shirt I have?",
        'SQLQuery' : "SELECT sum(stock_quantity) FROM t_shirts WHERE brand = 'Levi' AND color = 'White'",
        'SQLResult' : "Result of the SQL query",
        'Answer' : '151'}
]